# Copyright 2024 Tobias Kovats, Flavien Solt, ETH Zurich.
# Licensed under the General Public License, Version 3.0, see LICENSE for details.
# SPDX-License-Identifier: GPL-3.0-only
# TODO use config file instead
from enum import IntEnum, auto
import numpy as np
import os 

##
# MMU
##
USE_MMU_DEFAULT = True

##
# RVC
##
USE_COMPRESSED_DEFAULT = False

# NUM_MIN_BBS_LOWERBOUND = 100 if USE_MMU else 10
NUM_MIN_BBS_LOWERBOUND_DEFAULT = 10 # Used this for BOOM
NUM_MAX_BBS_UPPERBOUND_DEFAULT = 300
NUM_BBS_DEFAULT = 0 # When set to a positive value, fixes the number of BBs.
NUM_MAX_N_INSTRS_DEFAULT = 0 # When set to positive value, sets upper bound on program length
# Tainting the immediates might taint the PC if instruction code is loaded and speculated on.
TAINT_IMMRD_IMM_DEFAULT = False
TAINT_REGIMM_IMM_DEFAULT = False
TAINT_NONTAKEN_BRANCH_IMM_DEFAULT = False
ALLOW_NONTAKEN_BRANCHES_IN_TAINT_SOURCE_PRIVS_DEFAULT = True
ALLOW_TAKEN_BRANCHES_IN_TAINT_SOURCE_PRIVS_DEFAULT = True
ALLOW_INDIRECT_JUMPS_IN_TAINT_SOURCE_PRIVS_DEFAULT = True
ALLOW_NONTAKEN_BRANCHES_IN_TAINT_SINK_PRIVS_DEFAULT = True
ALLOW_NONTAKEN_BRANCHES_IN_NEUTRAL_PRIVS_DEFAULT = False
ALLOW_JALR_IN_NEUTRAL_PRIVS_DEFAULT = False
ALLOW_BRANCH_IN_NEUTRAL_PRIVS_DEFAULT = False
ALLOW_LOAD_PAGE_FAULT_IN_TAINT_SOURCE_PRIVS_DEFAULT = False
ALLOW_LOAD_PAGE_FAULT_IN_TAINT_SINK_PRIVS_DEFAULT = True
DISABLE_COMPUTATION_ON_TAINT_DEFAULT = False
TAINT_SOURCE_PRIVS_DEFAULT = None
TAINT_SINK_PRIVS_DEFAULT = None
MAX_N_TAINT_SOURCE_LAYOUTS_DEFAULT = -1
MIN_N_TAINT_SOURCE_LAYOUTS_DEFAULT = -1
MAX_GADGET_N_INSTR_DEFAULT = 8
FILL_MEM_WITH_DEAD_CODE_DEFAULT=True
DEAD_CODE_ONLY_IN_USED_PAGES_DEFAULT=True
STOP_AT_PC_TAINT_DEFAULT = False