NOPIZE_SANDWICH_INSTRUCTIONS_DEFAULT = False
FLATTEN_SANDWICH_INSTRUCTIONS_DEFAULT = False
REDUCE_TAINT_DEFAULT = False
REDUCE_DEAD_CODE_DEFAULT =False 
FIND_PILLARS_DEFAULT = True
FIND_PILLAR_INSTRUCTION_DEFAULT = True
DOUBLECHECK_MODELSIM_DEFAULT = True
CHECK_LEAKER_INVARIANCE_DEFAULT = False
# To speedup reduction testing when already known
FAILING_BB_ID_DEFAULT = -1
FAILING_INSTR_ID_DETAULT = -1
PILLAR_BB_ID_DEFAULT = -1
PILLAR_INSTR_ID_DEFAULT = -1