NOPIZE_SANDWICH_INSTRUCTIONS_DEFAULT = False
FLATTEN_SANDWICH_INSTRUCTIONS_DEFAULT = False
REDUCE_TAINT_DEFAULT = True
REDUCE_DEAD_CODE_DEFAULT = True
FIND_PILLARS_DEFAULT = False
FIND_PILLAR_INSTRUCTION_DEFAULT = False
DOUBLECHECK_MODELSIM_DEFAULT = True
CHECK_LEAKER_INVARIANCE_DEFAULT = True
# To speedup reduction testing when already known
FAILING_BB_ID_DEFAULT = -1
FAILING_INSTR_ID_DETAULT = -1
PILLAR_BB_ID_DEFAULT = -1
PILLAR_INSTR_ID_DEFAULT = -1